---
ibm_cloud_power:
  api_key: IBM_CLOUD_POWERVS_API_KEY
  cloud_instance_id: IBM_CLOUD_POWERVS_INSTANCE_ID
  ibmcloud_region: us-east
ibm_cloud_vpc:
  api_key: IBM_CLOUD_VPC_API_KEY
ibm_cloud_object_storage:
  api_key: IBM_CLOUD_OBJECT_STORAGE_API_KEY
  access_key: IBM_CLOUD_OBJECT_STORAGE_ACCESS_KEY
  secret_key: IBM_CLOUD_OBJECT_STORAGE_SECRET_KEY
iks:
  api_key: IBM_CLOUD_IKS_API_KEY
  hostname: ibm-cloud-iks-hostname
  port: 1234
