---
test:
  ibm_cloud_power_defaults: &ibm_cloud_power_defaults
    api_key: IBM_CLOUD_POWERVS_API_KEY
    cloud_instance_id: IBM_CLOUD_POWERVS_INSTANCE_ID
    ibmcloud_region: us-east
  ibm_cloud_power:
    <<: *ibm_cloud_power_defaults
  ibm_cloud_vpc_defaults: &ibm_cloud_vpc_defaults
    api_key: IBM_CLOUD_VPC_API_KEY
  ibm_cloud_vpc:
    <<: *ibm_cloud_vpc_defaults
  ibm_cloud_object_storage_defaults: &ibm_cloud_object_storage_defaults
    api_key: IBM_CLOUD_OBJECT_STORAGE_API_KEY
    access_key: IBM_CLOUD_OBJECT_STORAGE_ACCESS_KEY
    secret_key: IBM_CLOUD_OBJECT_STORAGE_SECRET_KEY
  ibm_cloud_object_storage:
    <<: *ibm_cloud_object_storage_defaults
  iks_defaults: &iks_defaults
    api_key: IBM_CLOUD_IKS_API_KEY
    hostname: ibm-cloud-iks-hostname
    port: 1234
  iks:
    <<: *iks_defaults
