#!/usr/bin/env ruby

ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../../../../../../Gemfile', __dir__)
require 'bundler/setup' if File.exist?(ENV['BUNDLE_GEMFILE'])

require_relative 'event_catcher'

def build_logger
  require 'manageiq-loggers'

  if ENV.fetch('CONTAINER', nil)
    ManageIQ::Loggers::Container.new
  elsif ENV.fetch('APPLIANCE', nil)
    ManageIQ::Loggers::Journald.new
  else
    ManageIQ::Loggers::Base.new($stdout)
  end
end

def parse_args
  require 'json'

  JSON.parse($stdin.read)
rescue JSON::ParserError
  abort('Invalid argument format')
end

def main(args)
  logger = build_logger
  logger.progname = 'evm'

  ems            = args['ems'].find { |m| m['type'] == 'ManageIQ::Providers::IbmCloud::ContainerManager' }
  endpoint       = ems['endpoints'].find { |e| e['role'] == 'default' }
  authentication = ems['authentications'].find { |a| a['authtype'] == 'bearer' }
  settings       = args['settings']
  messaging      = args['messaging']&.transform_keys(&:to_sym) || {}

  EventCatcher.new(ems, endpoint, authentication, settings, messaging, logger).run!
end

main(parse_args)
