---
name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: 0 0 * * *
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
        - '3.3'
    steps:
    - uses: actions/checkout@v4
    - run: |
        git --version
        echo "------------------"
        git config --list
    - name: Set up system
      run: bin/before_install
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby-version }}"
        bundler-cache: true
      timeout-minutes: 30
    - run: |
        pushd $(gem which manageiq-ui-classic)
        git config --list
        popd
    - uses: actions/upload-artifact@v4
      with:
        name: cache
        path: vendor/bundle/
